//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.29 at 09:55:44 AM BDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://interfaces.soap.zakir.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.zakir.soap.interfaces;
